### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_STIRR#9]
```
version: '2.1'
services:
  fhdhr_stirr:
    image: fhdhr_stirr:0.4.6
    container_name: fhdhr_stirr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 1900:1900 # SSD cluster port
      - 5004:5004 # Web and HDHR port
    volumes:
      - /<docker-config-directory>/fhdhr_stirr:/app/config
    restart: always
```
